# Generated by Django 4.0.4 on 2022-07-26 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_price', models.IntegerField()),
                ('user', models.ManyToManyField(related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=100)),
                ('highest_bid', models.ManyToManyField(blank=True, related_name='listings', to='auctions.bids')),
                ('user', models.ManyToManyField(related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('user', models.ManyToManyField(related_name='comments', to='auctions.listings')),
            ],
        ),
    ]
