# Generated by Django 4.0.4 on 2022-07-27 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_listings_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ManyToManyField(related_name='comments', to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='listings',
            name='desired_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='listings',
            name='user',
        ),
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
