# Generated by Django 4.0.4 on 2022-07-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments_listing_listings_desired_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
