# Generated by Django 4.0.4 on 2022-07-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
