# Generated by Django 4.0.4 on 2022-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_id_alter_listings_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='listing_title',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
