# Generated by Django 4.0.4 on 2022-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bids_listing_title_bids_listing_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='listing',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
