# Generated by Django 4.0.4 on 2022-08-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listings_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bid',
        ),
    ]
