# Generated by Django 4.0.4 on 2022-08-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
            preserve_default=False,
        ),
    ]
