# Generated by Django 4.0.4 on 2022-08-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
    ]
